==> /var/log/alternatives.log <==

==> /var/log/apply_ssh_ratelimit.log <==

==> /var/log/apport.log <==

==> /var/log/auth.log <==
2025-09-10T23:12:00.076407+00:00 eob-250501a sshd[2430]: Received disconnect from 207.180.229.239 port 45056:11: Bye Bye [preauth]
2025-09-10T23:12:00.077833+00:00 eob-250501a sshd[2430]: Disconnected from authenticating user root 207.180.229.239 port 45056 [preauth]
2025-09-10T23:12:12.371286+00:00 eob-250501a sshd[2470]: Accepted publickey for root from 91.126.43.112 port 17124 ssh2: RSA SHA256:YUDRPAU115MCwkF4S/wLFXV0Y7kLUTQ4QUL7H3Lc0ac
2025-09-10T23:12:12.375020+00:00 eob-250501a sshd[2470]: pam_unix(sshd:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T23:12:12.398245+00:00 eob-250501a systemd-logind[736]: New session 3 of user root.
2025-09-10T23:12:12.428642+00:00 eob-250501a (systemd): pam_unix(systemd-user:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T23:12:30.568546+00:00 eob-250501a CRON[955]: pam_unix(cron:session): session closed for user root
2025-09-10T23:13:07.436522+00:00 eob-250501a sshd[2976]: Invalid user test3 from 207.180.229.239 port 43132
2025-09-10T23:13:07.460591+00:00 eob-250501a sshd[2976]: Received disconnect from 207.180.229.239 port 43132:11: Bye Bye [preauth]
2025-09-10T23:13:07.460733+00:00 eob-250501a sshd[2976]: Disconnected from invalid user test3 207.180.229.239 port 43132 [preauth]
2025-09-10T23:14:12.486983+00:00 eob-250501a sshd[5374]: Invalid user UBUNTU from 207.180.229.239 port 41202
2025-09-10T23:14:12.500786+00:00 eob-250501a sshd[5374]: Received disconnect from 207.180.229.239 port 41202:11: Bye Bye [preauth]
2025-09-10T23:14:12.500942+00:00 eob-250501a sshd[5374]: Disconnected from invalid user UBUNTU 207.180.229.239 port 41202 [preauth]
2025-09-10T23:14:27.580304+00:00 eob-250501a sshd[5446]: Received disconnect from 193.46.255.33 port 48372:11:  [preauth]
2025-09-10T23:14:27.584360+00:00 eob-250501a sshd[5446]: Disconnected from authenticating user root 193.46.255.33 port 48372 [preauth]
2025-09-10T23:15:01.574753+00:00 eob-250501a CRON[6046]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T23:15:01.581759+00:00 eob-250501a CRON[6046]: pam_unix(cron:session): session closed for user root
2025-09-10T23:15:17.217968+00:00 eob-250501a sshd[6079]: Invalid user odoo from 207.180.229.239 port 39272
2025-09-10T23:15:17.227741+00:00 eob-250501a sshd[6079]: Received disconnect from 207.180.229.239 port 39272:11: Bye Bye [preauth]
2025-09-10T23:15:17.227863+00:00 eob-250501a sshd[6079]: Disconnected from invalid user odoo 207.180.229.239 port 39272 [preauth]

==> /var/log/batch_attacking_logs.log <==
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 170
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 170
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/batch_ip_geolocation.log <==
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 14, in <module>
    DB_HOST = os.getenv("DB_HOST", "localhost")
              ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

==> /var/log/batch_kern_logs.log <==
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 0
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 0
2025-08-24 18:30:03 [🔍]: No hay nuevas líneas en el log.

==> /var/log/cloud-init-output.log <==
ci-info: |   3   | 165.22.80.0 |   0.0.0.0   | 255.255.240.0 |    eth0   |   U   |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   0   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   1   |  fe80::/64  |    ::   |    eth1   |   U   |
ci-info: |   3   |    local    |    ::   |    eth1   |   U   |
ci-info: |   4   |    local    |    ::   |    eth0   |   U   |
ci-info: |   5   |  multicast  |    ::   |    eth0   |   U   |
ci-info: |   6   |  multicast  |    ::   |    eth1   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
+ cloud-init-per instance do-resolved-conf /bin/false
+ exit 0
+ logger -t DigitalOcean adding random seed to /dev/urandom
+ base64 -d
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:config' at Wed, 10 Sep 2025 23:11:31 +0000. Up 12.52 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:final' at Wed, 10 Sep 2025 23:11:36 +0000. Up 17.39 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Wed, 10 Sep 2025 23:11:36 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 17.48 seconds

==> /var/log/cloud-init.log <==
2025-09-10 23:11:36,469 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-09-10 23:11:36,469 - helpers.py[DEBUG]: config-install_hotplug already ran (freq=once-per-instance)
2025-09-10 23:11:36,470 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug previously ran
2025-09-10 23:11:36,470 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-09-10 23:11:36,470 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-09-10 23:11:36,470 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x7e0f6ef6e210>)
2025-09-10 23:11:36,470 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-10 23:11:36,470 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-10 23:11:36,482 - performance.py[DEBUG]: Rendering jinja2 template took 0.012 seconds
2025-09-10 23:11:36,482 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Wed, 10 Sep 2025 23:11:36 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 17.48 seconds
2025-09-10 23:11:36,482 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2025-09-10 23:11:36,490 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.020 seconds
2025-09-10 23:11:36,490 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-09-10 23:11:36,490 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-10 23:11:36,490 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-10 23:11:36,495 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpvj2bz3j8) - w: [644] 533 bytes/chars
2025-09-10 23:11:36,496 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpi8h_qjwl) - w: [644] 101 bytes/chars
2025-09-10 23:11:36,498 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-09-10 23:11:36,499 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.150 seconds
2025-09-10 23:11:36,499 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final

==> /var/log/configure_docker_limits.log <==
2025-09-10 23:12:30 [✅]: Docker está en ejecución.
2025-09-10 23:12:30 [🔍]: Verificando el contenedor ac4b55470ca9...
2025-09-10 23:12:30 [⚙️]: Aplicando límites al contenedor ac4b55470ca9...
ac4b55470ca9
2025-09-10 23:12:30 [✅]: Límites aplicados correctamente a ac4b55470ca9.
2025-09-10 23:12:30 [🔍]: Verificando el contenedor 53d3f808366a...
2025-09-10 23:12:30 [⚙️]: Aplicando límites al contenedor 53d3f808366a...
53d3f808366a
2025-09-10 23:12:30 [✅]: Límites aplicados correctamente a 53d3f808366a.
2025-09-10 23:12:30 [🔍]: Verificando el contenedor 214b26e61ea8...
2025-09-10 23:12:30 [⚙️]: Aplicando límites al contenedor 214b26e61ea8...
214b26e61ea8
2025-09-10 23:12:30 [✅]: Límites aplicados correctamente a 214b26e61ea8.
2025-09-10 23:12:30 [🔍]: Verificando el contenedor d15ed24954aa...
2025-09-10 23:12:30 [⚙️]: Aplicando límites al contenedor d15ed24954aa...
d15ed24954aa
2025-09-10 23:12:30 [✅]: Límites aplicados correctamente a d15ed24954aa.
2025-09-10 23:12:30 [🔍]: Verificando el contenedor 2845a26076ba...
2025-09-10 23:12:30 [ℹ️]: El contenedor 2845a26076ba ya tiene límites configurados.
2025-09-10 23:12:30 [🎯]: Proceso de configuración de límites completado.

==> /var/log/docker_resources.log <==
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'

==> /var/log/docker_resources_history.log <==
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | 3c9ebefd8d2d | 51.32MiB / No definido (N/A %)   | 51.32MiB / No definido (N/A %)   | N/A % / No definido           | captain-captain.1.nqmy79ajr06glvpd8f51ggh49                      
dr-info: | 7f13309d6403 | 1.582MiB / 393 MiB (0.5 %)       | 1.582MiB / 786 MiB (0.3 %)       | N/A % / 100 MiliCores         | captain-certbot.1.m009zohpfl8zfk2w8isdqc5l0                      
dr-info: | 85e0f44c1489 | 0B / 393 MiB (0.0 %)             | 0B / 786 MiB (0.0 %)             | N/A % / 100 MiliCores         | captain-nginx.1.qtfkqqcyxtiq40dq9116b8zyo                        
dr-info: | 99aba7115a2a | 59.97MiB / 393 MiB (15.3 %)      | 59.97MiB / 786 MiB (7.6 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.gtcghw45t9o2im9q839g9dqjl       
dr-info: | 2845a26076ba | 7.27MiB / 393 MiB (1.8 %)        | 7.27MiB / 786 MiB (0.9 %)        | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: ===== 2025-08-24 18:30:01 =====
dr-info: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Docker Resources+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | d37816bebd3a | 1.617MiB / No definido (N/A %)   | 1.617MiB / No definido (N/A %)   | N/A % / No definido           | captain-certbot.1.00kqlkv25xs6gey72705immyq                      
dr-info: | 5b28c617fae9 | 2.707MiB / 393 MiB (0.8 %)       | 2.707MiB / 786 MiB (0.4 %)       | N/A % / 100 MiliCores         | captain-nginx.1.if8neg7tjaqcsuoksrmpfygih                        
dr-info: | 700d23dbd7e3 | 38.99MiB / 393 MiB (9.9 %)       | 38.99MiB / 786 MiB (5.0 %)       | N/A % / 100 MiliCores         | captain-captain.1.hxqcsby7v3gjfzu9h82xttpsp                      
dr-info: | 3612e9a401d3 | 56.09MiB / 393 MiB (14.2 %)      | 56.09MiB / 786 MiB (7.1 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.tmovpk0y629d30g34zif2rucr       
dr-info: | 2845a26076ba | 7.195MiB / 393 MiB (1.8 %)       | 7.195MiB / 786 MiB (0.9 %)       | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+

==> /var/log/dpkg.log <==
2025-09-06 06:36:48 startup archives unpack
2025-09-06 06:36:49 upgrade do-agent:amd64 3.16.11 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.16.11
2025-09-06 06:36:49 status half-installed do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 startup packages configure
2025-09-06 06:36:49 configure do-agent:amd64 3.18.2 <none>
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.18.2
2025-09-06 06:36:50 status installed do-agent:amd64 3.18.2

==> /var/log/droplet-agent.update.log <==
Waiting 748 seconds
Checking architecture support...OK
Preparing to check for update
Package Host: https://repos-droplet.digitalocean.com
Package Path: apt/droplet-agent/pool/main/main/d/droplet-agent/droplet-agent_
Keyring Path: apt/droplet-agent/pool/main/main/d/droplet-agent-keyring/droplet-agent-keyring_
Local Keyring:2.0.0
Local Version:1.2.11
Checking Latest Version...
Latest keyring package:2.0.0
Latest agent package:1.2.1
Updating droplet-agent deb package

==> /var/log/fail2ban.log <==
2025-09-10 23:11:30,998 fail2ban.jail           [916]: INFO    Creating new jail 'nginx-limit-req'
2025-09-10 23:11:30,998 fail2ban.jail           [916]: INFO    Jail 'nginx-limit-req' uses systemd {}
2025-09-10 23:11:31,011 fail2ban.jail           [916]: INFO    Initiated 'systemd' backend
2025-09-10 23:11:31,017 fail2ban.filtersystemd  [916]: INFO    [nginx-limit-req] Added journal match for: '_SYSTEMD_UNIT=nginx.service + _COMM=nginx'
2025-09-10 23:11:31,017 fail2ban.filter         [916]: INFO      maxRetry: 20
2025-09-10 23:11:31,017 fail2ban.filter         [916]: INFO      findtime: 60
2025-09-10 23:11:31,017 fail2ban.actions        [916]: INFO      banTime: 3600
2025-09-10 23:11:31,018 fail2ban.filter         [916]: INFO      encoding: UTF-8
2025-09-10 23:11:31,018 fail2ban.transmitter    [916]: ERROR   Jail 'nginx-badbots' skipped, because of wrong configuration: Unable to read the filter 'nginx-badbots'
2025-09-10 23:11:31,018 fail2ban.transmitter    [916]: ERROR   Jail 'nginx-noscript' skipped, because of wrong configuration: Unable to read the filter 'nginx-noscript'
2025-09-10 23:11:31,025 fail2ban.jail           [916]: INFO    Jail 'sshd' started
2025-09-10 23:11:31,030 fail2ban.jail           [916]: INFO    Jail 'nginx-http-auth' started
2025-09-10 23:11:31,040 fail2ban.jail           [916]: INFO    Jail 'nginx-limit-req' started
2025-09-10 23:11:31,334 fail2ban.filtersystemd  [916]: INFO    [nginx-http-auth] Jail is in operation now (process new journal entries)
2025-09-10 23:11:31,335 fail2ban.filtersystemd  [916]: INFO    [nginx-limit-req] Jail is in operation now (process new journal entries)
2025-09-10 23:11:31,751 fail2ban.filtersystemd  [916]: INFO    [sshd] Jail is in operation now (process new journal entries)
2025-09-10 23:13:07,933 fail2ban.filter         [916]: INFO    [sshd] Found 207.180.229.239 - 2025-09-10 23:13:07
2025-09-10 23:14:12,680 fail2ban.filter         [916]: INFO    [sshd] Found 207.180.229.239 - 2025-09-10 23:14:12
2025-09-10 23:15:17,428 fail2ban.filter         [916]: INFO    [sshd] Found 207.180.229.239 - 2025-09-10 23:15:17
2025-09-10 23:15:17,709 fail2ban.actions        [916]: NOTICE  [sshd] Ban 207.180.229.239

==> /var/log/kern.log <==

==> /var/log/log_fail2ban_logs.log <==
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 230
2025-08-24 18:30:03 [⚡]: Líneas después del filtrado: 230
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 230
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/mail.log <==
