==> /var/log/alternatives.log <==

==> /var/log/apply_ssh_ratelimit.log <==

==> /var/log/apport.log <==

==> /var/log/auth.log <==
2025-09-09T00:41:01.354002+00:00 eob-250501a CRON[951]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-09T00:41:01.544085+00:00 eob-250501a sshd[968]: Server listening on :: port 22.
2025-09-09T00:41:01.544241+00:00 eob-250501a CRON[950]: pam_unix(cron:session): session closed for user root
2025-09-09T00:41:02.981410+00:00 eob-250501a sshd[998]: Connection closed by authenticating user root 103.190.8.4 port 52632 [preauth]
2025-09-09T00:41:04.660690+00:00 eob-250501a sshd[1049]: Connection closed by authenticating user root 103.190.8.4 port 52646 [preauth]
2025-09-09T00:41:06.256103+00:00 eob-250501a sshd[1419]: Connection closed by authenticating user root 103.190.8.4 port 34146 [preauth]
2025-09-09T00:41:07.910213+00:00 eob-250501a sshd[1536]: Connection closed by authenticating user root 103.190.8.4 port 34158 [preauth]
2025-09-09T00:41:09.562049+00:00 eob-250501a sshd[1642]: Connection closed by authenticating user root 103.190.8.4 port 34172 [preauth]
2025-09-09T00:41:11.218186+00:00 eob-250501a sshd[1663]: Connection closed by authenticating user root 103.190.8.4 port 34178 [preauth]
2025-09-09T00:41:12.797972+00:00 eob-250501a sshd[1681]: Connection closed by authenticating user root 103.190.8.4 port 34184 [preauth]
2025-09-09T00:41:14.527840+00:00 eob-250501a sshd[1798]: Connection closed by authenticating user root 103.190.8.4 port 34194 [preauth]
2025-09-09T00:41:16.132008+00:00 eob-250501a sshd[2202]: Connection closed by authenticating user root 103.190.8.4 port 56312 [preauth]
2025-09-09T00:41:17.706199+00:00 eob-250501a sshd[2217]: Connection closed by authenticating user root 103.190.8.4 port 56328 [preauth]
2025-09-09T00:41:26.524917+00:00 eob-250501a sshd[2247]: Accepted publickey for root from 91.126.43.112 port 17274 ssh2: RSA SHA256:YUDRPAU115MCwkF4S/wLFXV0Y7kLUTQ4QUL7H3Lc0ac
2025-09-09T00:41:26.527248+00:00 eob-250501a sshd[2247]: pam_unix(sshd:session): session opened for user root(uid=0) by root(uid=0)
2025-09-09T00:41:26.555537+00:00 eob-250501a systemd-logind[737]: New session 3 of user root.
2025-09-09T00:41:26.596121+00:00 eob-250501a (systemd): pam_unix(systemd-user:session): session opened for user root(uid=0) by root(uid=0)
2025-09-09T00:42:02.236427+00:00 eob-250501a CRON[951]: pam_unix(cron:session): session closed for user root
2025-09-09T00:45:01.246032+00:00 eob-250501a CRON[5510]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-09T00:45:01.256757+00:00 eob-250501a CRON[5510]: pam_unix(cron:session): session closed for user root

==> /var/log/batch_attacking_logs.log <==
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 170
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 170
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/batch_ip_geolocation.log <==
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 14, in <module>
    DB_HOST = os.getenv("DB_HOST", "localhost")
              ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

==> /var/log/batch_kern_logs.log <==
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 0
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 0
2025-08-24 18:30:03 [🔍]: No hay nuevas líneas en el log.

==> /var/log/cloud-init-output.log <==
ci-info: |   3   | 165.22.80.0 |   0.0.0.0   | 255.255.240.0 |    eth0   |   U   |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   0   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   1   |  fe80::/64  |    ::   |    eth1   |   U   |
ci-info: |   3   |    local    |    ::   |    eth1   |   U   |
ci-info: |   4   |    local    |    ::   |    eth0   |   U   |
ci-info: |   5   |  multicast  |    ::   |    eth0   |   U   |
ci-info: |   6   |  multicast  |    ::   |    eth1   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
+ cloud-init-per instance do-resolved-conf /bin/false
+ exit 0
+ logger -t DigitalOcean adding random seed to /dev/urandom
+ base64 -d
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:config' at Tue, 09 Sep 2025 00:41:03 +0000. Up 12.73 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:final' at Tue, 09 Sep 2025 00:41:08 +0000. Up 17.99 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Tue, 09 Sep 2025 00:41:08 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 18.08 seconds

==> /var/log/cloud-init.log <==
2025-09-09 00:41:08,582 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-09-09 00:41:08,582 - helpers.py[DEBUG]: config-install_hotplug already ran (freq=once-per-instance)
2025-09-09 00:41:08,582 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug previously ran
2025-09-09 00:41:08,582 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-09-09 00:41:08,582 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-09-09 00:41:08,582 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x7e6d5e590290>)
2025-09-09 00:41:08,582 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-09 00:41:08,583 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-09 00:41:08,594 - performance.py[DEBUG]: Rendering jinja2 template took 0.011 seconds
2025-09-09 00:41:08,595 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Tue, 09 Sep 2025 00:41:08 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 18.08 seconds
2025-09-09 00:41:08,596 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2025-09-09 00:41:08,596 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.014 seconds
2025-09-09 00:41:08,596 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-09-09 00:41:08,596 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-09 00:41:08,599 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-09 00:41:08,599 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpd9i7g0sr) - w: [644] 533 bytes/chars
2025-09-09 00:41:08,600 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpki88h871) - w: [644] 101 bytes/chars
2025-09-09 00:41:08,601 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-09-09 00:41:08,602 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.150 seconds
2025-09-09 00:41:08,602 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final

==> /var/log/configure_docker_limits.log <==
2025-09-09 00:42:01 [✅]: Docker está en ejecución.
2025-09-09 00:42:01 [🔍]: Verificando el contenedor 15c7e996640b...
2025-09-09 00:42:01 [⚙️]: Aplicando límites al contenedor 15c7e996640b...
15c7e996640b
2025-09-09 00:42:01 [✅]: Límites aplicados correctamente a 15c7e996640b.
2025-09-09 00:42:01 [🔍]: Verificando el contenedor ea8cfb98e442...
2025-09-09 00:42:01 [⚙️]: Aplicando límites al contenedor ea8cfb98e442...
ea8cfb98e442
2025-09-09 00:42:02 [✅]: Límites aplicados correctamente a ea8cfb98e442.
2025-09-09 00:42:02 [🔍]: Verificando el contenedor 913d58acf462...
2025-09-09 00:42:02 [⚙️]: Aplicando límites al contenedor 913d58acf462...
913d58acf462
2025-09-09 00:42:02 [✅]: Límites aplicados correctamente a 913d58acf462.
2025-09-09 00:42:02 [🔍]: Verificando el contenedor f8a350414a04...
2025-09-09 00:42:02 [⚙️]: Aplicando límites al contenedor f8a350414a04...
f8a350414a04
2025-09-09 00:42:02 [✅]: Límites aplicados correctamente a f8a350414a04.
2025-09-09 00:42:02 [🔍]: Verificando el contenedor 2845a26076ba...
2025-09-09 00:42:02 [ℹ️]: El contenedor 2845a26076ba ya tiene límites configurados.
2025-09-09 00:42:02 [🎯]: Proceso de configuración de límites completado.

==> /var/log/docker_resources.log <==
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'

==> /var/log/docker_resources_history.log <==
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | 3c9ebefd8d2d | 51.32MiB / No definido (N/A %)   | 51.32MiB / No definido (N/A %)   | N/A % / No definido           | captain-captain.1.nqmy79ajr06glvpd8f51ggh49                      
dr-info: | 7f13309d6403 | 1.582MiB / 393 MiB (0.5 %)       | 1.582MiB / 786 MiB (0.3 %)       | N/A % / 100 MiliCores         | captain-certbot.1.m009zohpfl8zfk2w8isdqc5l0                      
dr-info: | 85e0f44c1489 | 0B / 393 MiB (0.0 %)             | 0B / 786 MiB (0.0 %)             | N/A % / 100 MiliCores         | captain-nginx.1.qtfkqqcyxtiq40dq9116b8zyo                        
dr-info: | 99aba7115a2a | 59.97MiB / 393 MiB (15.3 %)      | 59.97MiB / 786 MiB (7.6 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.gtcghw45t9o2im9q839g9dqjl       
dr-info: | 2845a26076ba | 7.27MiB / 393 MiB (1.8 %)        | 7.27MiB / 786 MiB (0.9 %)        | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: ===== 2025-08-24 18:30:01 =====
dr-info: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Docker Resources+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | d37816bebd3a | 1.617MiB / No definido (N/A %)   | 1.617MiB / No definido (N/A %)   | N/A % / No definido           | captain-certbot.1.00kqlkv25xs6gey72705immyq                      
dr-info: | 5b28c617fae9 | 2.707MiB / 393 MiB (0.8 %)       | 2.707MiB / 786 MiB (0.4 %)       | N/A % / 100 MiliCores         | captain-nginx.1.if8neg7tjaqcsuoksrmpfygih                        
dr-info: | 700d23dbd7e3 | 38.99MiB / 393 MiB (9.9 %)       | 38.99MiB / 786 MiB (5.0 %)       | N/A % / 100 MiliCores         | captain-captain.1.hxqcsby7v3gjfzu9h82xttpsp                      
dr-info: | 3612e9a401d3 | 56.09MiB / 393 MiB (14.2 %)      | 56.09MiB / 786 MiB (7.1 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.tmovpk0y629d30g34zif2rucr       
dr-info: | 2845a26076ba | 7.195MiB / 393 MiB (1.8 %)       | 7.195MiB / 786 MiB (0.9 %)       | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+

==> /var/log/dpkg.log <==
2025-09-06 06:36:48 startup archives unpack
2025-09-06 06:36:49 upgrade do-agent:amd64 3.16.11 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.16.11
2025-09-06 06:36:49 status half-installed do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 startup packages configure
2025-09-06 06:36:49 configure do-agent:amd64 3.18.2 <none>
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.18.2
2025-09-06 06:36:50 status installed do-agent:amd64 3.18.2

==> /var/log/droplet-agent.update.log <==
Waiting 748 seconds
Checking architecture support...OK
Preparing to check for update
Package Host: https://repos-droplet.digitalocean.com
Package Path: apt/droplet-agent/pool/main/main/d/droplet-agent/droplet-agent_
Keyring Path: apt/droplet-agent/pool/main/main/d/droplet-agent-keyring/droplet-agent-keyring_
Local Keyring:2.0.0
Local Version:1.2.11
Checking Latest Version...
Latest keyring package:2.0.0
Latest agent package:1.2.1
Updating droplet-agent deb package

==> /var/log/fail2ban.log <==
2025-09-09 00:41:03,172 fail2ban.filter         [916]: INFO      encoding: UTF-8
2025-09-09 00:41:03,172 fail2ban.jail           [916]: INFO    Creating new jail 'nginx-limit-req'
2025-09-09 00:41:03,172 fail2ban.jail           [916]: INFO    Jail 'nginx-limit-req' uses systemd {}
2025-09-09 00:41:03,184 fail2ban.jail           [916]: INFO    Initiated 'systemd' backend
2025-09-09 00:41:03,189 fail2ban.filtersystemd  [916]: INFO    [nginx-limit-req] Added journal match for: '_SYSTEMD_UNIT=nginx.service + _COMM=nginx'
2025-09-09 00:41:03,190 fail2ban.filter         [916]: INFO      maxRetry: 20
2025-09-09 00:41:03,192 fail2ban.filter         [916]: INFO      findtime: 60
2025-09-09 00:41:03,194 fail2ban.actions        [916]: INFO      banTime: 3600
2025-09-09 00:41:03,196 fail2ban.filter         [916]: INFO      encoding: UTF-8
2025-09-09 00:41:03,197 fail2ban.transmitter    [916]: ERROR   Jail 'nginx-badbots' skipped, because of wrong configuration: Unable to read the filter 'nginx-badbots'
2025-09-09 00:41:03,197 fail2ban.transmitter    [916]: ERROR   Jail 'nginx-noscript' skipped, because of wrong configuration: Unable to read the filter 'nginx-noscript'
2025-09-09 00:41:03,220 fail2ban.jail           [916]: INFO    Jail 'sshd' started
2025-09-09 00:41:03,225 fail2ban.jail           [916]: INFO    Jail 'nginx-http-auth' started
2025-09-09 00:41:03,235 fail2ban.jail           [916]: INFO    Jail 'nginx-limit-req' started
2025-09-09 00:41:03,402 fail2ban.actions        [916]: NOTICE  [sshd] Restore Ban 189.36.132.232
2025-09-09 00:41:03,655 fail2ban.filtersystemd  [916]: INFO    [nginx-http-auth] Jail is in operation now (process new journal entries)
2025-09-09 00:41:03,663 fail2ban.filtersystemd  [916]: INFO    [nginx-limit-req] Jail is in operation now (process new journal entries)
2025-09-09 00:41:03,932 fail2ban.actions        [916]: NOTICE  [sshd] Restore Ban 2.188.239.248
2025-09-09 00:41:04,025 fail2ban.actions        [916]: NOTICE  [sshd] Restore Ban 64.225.103.75
2025-09-09 00:41:04,283 fail2ban.filtersystemd  [916]: INFO    [sshd] Jail is in operation now (process new journal entries)

==> /var/log/kern.log <==

==> /var/log/log_fail2ban_logs.log <==
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 230
2025-08-24 18:30:03 [⚡]: Líneas después del filtrado: 230
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 230
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/mail.log <==
